// Auditing the written notes on a sense.
//
// The notes are generated by Haiku in whatever language the learner reads, and
// the Ukrainian ones come back with defects a learner cannot catch — they have
// no way to know that "регулярний дієслово" is wrong, or that "más" is Spanish.
//
// This reports only what it can be SURE of. A note that is merely clumsy is not
// a finding: a checker that cries wolf gets switched off, and then it catches
// nothing at all. Everything here is either a script-level impossibility or a
// disagreement inside a closed vocabulary.
//
// What it deliberately does NOT catch: notes that are well-formed Ukrainian and
// simply wrong ("hingegen is a Сполучник" — it is an adverb). Those need a
// reviewer, not a regex, and pretending otherwise would hide them.

const TEXT_FIELDS = [
  ['explanation', 'explanation'],
  ['grammar_note', 'grammarNote'],
  ['usage_note', 'usageNote'],
  ['translation', 'translation'],
]

const CYRILLIC = /[Ѐ-ԯ]/
const LATIN = /[A-Za-zÀ-ɏ]/
// Anything outside Latin, Cyrillic, digits, whitespace and general punctuation.
// Combining marks pass through here — a stress mark is its own, more specific
// finding, and reporting it twice would be noise.
const OTHER_SCRIPT = /[^ -ɏ̀-ͯЀ-ԯ -⁯\s]/
// A stress mark. Ukrainian prose does not carry one; where it appears, the word
// has been truncated or copied out of a dictionary entry mid-inflection.
const STRESS = /[́´]/
// Letters Russian has and Ukrainian does not.
const RUSSIAN_ONLY = /[ыъэёЫЪЭЁ]/

// Russian words spelled entirely in letters Ukrainian also has, so the letter
// rule walks straight past them: "мідного или золотого", "тщательно шукати",
// "это настоящее чистилище". Membership is strict — a word earns a place here
// only if it has NO Ukrainian reading at all. That is why "души" (Russian for
// souls, but also the Ukrainian genitive of душа), "все", "так" and "через"
// are deliberately absent: each is ordinary Ukrainian in some sentence, and a
// checker that flags correct writing is a checker that gets switched off.
const RUSSIAN_WORDS = new Set([
  'или', 'это', 'этот', 'эта', 'эти', 'что', 'чтобы', 'если', 'как',
  'тоже', 'также', 'очень', 'сейчас', 'всегда', 'здесь', 'тщательно',
  'настоящий', 'настоящая', 'настоящее', 'нужно', 'может', 'можно',
  'используется', 'используются', 'значит', 'только', 'когда', 'где',
  'почему', 'потому', 'вместо', 'между', 'после', 'более', 'нет',
  'который', 'которая', 'которые', 'другой', 'каждый', 'самый',
  'его', 'ее', 'их', 'она', 'они', 'был', 'была', 'было', 'были', 'есть',
  'время', 'лицо', 'дело', 'вещь', 'сила',
])
// Latin letters carrying a diacritic that German never uses. German's own
// (ä ö ü Ä Ö Ü ß) are excluded, so a German word in a Ukrainian note is fine.
const FOREIGN_DIACRITIC = /[À-ɏ]/
const GERMAN_LETTERS = /[äöüÄÖÜß]/

// Hyphens split too: a Latin acronym hyphenated onto a Ukrainian word
// ("GPS-маяки") is ordinary writing, not a word spliced out of two scripts.
const tokens = (s) => s.split(/[\s·;,()«»"'—–-]+/).filter(Boolean)

// The closed vocabulary of a grammar note. Agreement inside it is checkable
// precisely because the vocabulary is small; outside it the audit says nothing.
const NOUN_GENDER = {
  'дієслово': 'n', 'слово': 'n', 'закінчення': 'n', 'значення': 'n',
  'доповнення': 'n', 'вживання': 'n', 'число': 'n', 'речення': 'n',
  'питання': 'n', 'правило': 'n', 'відмінювання': 'n',
  'іменник': 'm', 'прикметник': 'm', 'займенник': 'm', 'прийменник': 'm',
  'відмінок': 'm', 'артикль': 'm', 'рід': 'm', 'наголос': 'm', 'префікс': 'm',
  'термін': 'm', 'стан': 'm', 'додаток': 'm', 'прислівник': 'm',
  'сполучник': 'm', 'дієприкметник': 'm',
  'форма': 'f', 'конструкція': 'f', 'відміна': 'f', 'частка': 'f',
  'основа': 'f', 'позиція': 'f', 'група': 'f', 'множина': 'f', 'однина': 'f',
}
const ADJ_STEMS = [
  'регулярн', 'нерегулярн', 'правильн', 'неправильн', 'перехідн', 'неперехідн',
  'зворотн', 'сильн', 'слабк', 'модальн', 'допоміжн', 'означен', 'неозначен',
  'відокремлюван', 'невідокремлюван', 'множинн', 'однинн', 'безособов', 'особов',
  // Countability and register, which these notes reach for as readily as they
  // reach for "правильний" — and which the check was blind to.
  'лічильн', 'лічуван', 'обчислюван', 'незлічуван', 'незчисленн',
  'формальн', 'неформальн', 'технічн', 'спеціалізован', 'числов',
  'атрибутивн', 'предикативн', 'переносн', 'буквальн', 'розмовн', 'метафоричн',
]
const ADJ_ENDINGS = { 'ий': 'm', 'ій': 'm', 'а': 'f', 'я': 'f', 'е': 'n', 'є': 'n' }
const GENDER_NAME = { m: 'чоловічого', f: 'жіночого', n: 'середнього' }

function adjectiveGender(word) {
  const w = word.toLowerCase()
  for (const stem of ADJ_STEMS) {
    if (!w.startsWith(stem)) continue
    const ending = w.slice(stem.length)
    if (ending in ADJ_ENDINGS) return ADJ_ENDINGS[ending]
  }
  return null
}

function fieldsOf(sense) {
  return TEXT_FIELDS
    .map(([snake, camel]) => [snake, sense[snake] ?? sense[camel]])
    .filter(([, v]) => typeof v === 'string' && v.trim())
}

// Any Cyrillic at all makes a note Cyrillic. That is deliberate: a single
// Ukrainian phrase spliced into an English note ("Uncountable як колективне")
// is exactly the defect this is looking for.
function scriptOf(text) {
  if (CYRILLIC.test(text)) return 'cyrillic'
  return LATIN.test(text) ? 'latin' : null
}

export function auditSense(sense) {
  const found = []
  const fields = fieldsOf(sense)
  const add = (code, field, excerpt, detail) => found.push({ code, field, excerpt, detail })

  for (const [field, text] of fields) {
    const other = text.match(OTHER_SCRIPT)
    if (other) add('foreign-script', field, other[0], 'a script that is neither Latin nor Cyrillic')

    const stressed = tokens(text).find((w) => STRESS.test(w))
    if (stressed) add('stress-mark', field, stressed, 'a stress mark, so the word is truncated or half-inflected')

    const ru = text.match(RUSSIAN_ONLY)
    if (ru) add('russian-letter', field, ru[0], 'a letter Russian has and Ukrainian does not')

    for (const word of tokens(text)) {
      if (RUSSIAN_WORDS.has(word.toLowerCase().replace(/[.:!?]+$/, ''))) {
        add('russian-word', field, word, 'a Russian word with no Ukrainian reading')
      }
    }

    if (CYRILLIC.test(text)) {
      const mixedWord = tokens(text).find((w) => CYRILLIC.test(w) && LATIN.test(w))
      if (mixedWord) add('mixed-script-word', field, mixedWord, 'one word written half in Latin, half in Cyrillic')

      const foreign = tokens(text).find((w) => FOREIGN_DIACRITIC.test(w) && !GERMAN_LETTERS.test(w))
      if (foreign) add('foreign-diacritic', field, foreign, 'a diacritic German does not use, so the word is not German either')
    }

    // Agreement, inside the closed grammar vocabulary only.
    const ws = tokens(text)
    for (let i = 1; i < ws.length; i++) {
      const noun = NOUN_GENDER[ws[i].toLowerCase()]
      const adj = adjectiveGender(ws[i - 1])
      if (noun && adj && noun !== adj) {
        add('gender-agreement', field, ws[i - 1] + ' ' + ws[i],
          '"' + ws[i] + '" is ' + GENDER_NAME[noun] + ' роду, the adjective is ' + GENDER_NAME[adj])
      }
    }
  }

  // The notes of one sense should agree with each other, and the EXPLANATION is
  // the anchor: it is the meaning, the primary note, so a grammar or usage note
  // that disagrees with it is the one out of place. Majority voting cannot
  // settle a two-note sense, and guessing there put the finding on the wrong
  // field. `translation` takes no part: it is the gloss — an identifier in the
  // language the learner already has — and treating a Ukrainian gloss on an
  // English entry as a defect flagged 40 sound entries on the first run.
  const NOTE_FIELDS = ['explanation', 'grammar_note', 'usage_note']
  const notes = fields
    .filter(([field]) => NOTE_FIELDS.includes(field))
    .map(([field, text]) => [field, scriptOf(text)])
    .filter(([, script]) => script)

  const anchor = notes.find(([field]) => field === 'explanation') ?? notes[0]
  if (anchor) {
    const spoken = anchor[1] === 'cyrillic' ? 'Ukrainian' : 'English'
    for (const [field, script] of notes) {
      if (script !== anchor[1]) {
        add('mixed-language', field, null, `the meaning of this sense is written in ${spoken}`)
      }
    }
  }

  return found
}

export function auditDictionary(senses) {
  return senses.flatMap((s) => auditSense(s).map((f) => ({ word: s.word_form ?? s.wordForm, senseId: s.id, ...f })))
}
